### PR TITLE
Update MenuItemEditPage.php

### PR DESCRIPTION
**Pull request by kshitijSharma2014**

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@puneet0191 @javigomez 
removing menus errors/failures

**Comment by puneet0191** [comment]
@kshitijSharma2014 I tested this PR and found that we have a total of 7 errors left out in Menus, can you please fix them? 

One of the errors is similar to the one we are getting in Module Manager, change of Filter is causing the test to fail. 
Here is the log of errors:

Configuration read from /home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/phpunit.xml.dist

......EEEEE.....    EE......

Time: 24.69 minutes, Memory: 6.25Mb

There were 7 errors:

1) MenuItemsManager0001Test::editMenuItem_ChangeFields_FieldsChanged
SeleniumClient\Http\SeleniumNoSuchElementException:  An element could not be located on the page using the given search parameters. Unable to locate element: {"method":"xpath","selector":"//tbody/tr/td//a[contains(text(), 'Menu Item 449780797')]"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'puneet-ThinkPad-T430', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.13.0-43-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:73
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:26
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:350
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminManagerPage.php:50
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Menus/MenuItemsManagerPage.php:139
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0001Test.php:237

2) MenuItemsManager0002Test::addMenuItem_FrontEndCheck_MenuAdded
SeleniumClient\Http\SeleniumNoSuchElementException:  An element could not be located on the page using the given search parameters. Unable to locate element: {"method":"xpath","selector":"//thead//input[@name='checkall-toggle' or @name='toggle']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'puneet-ThinkPad-T430', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.13.0-43-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:73
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:26
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:350
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminManagerPage.php:38
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Menus/MenuItemsManagerPage.php:177
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0002Test.php:74

3) MenuItemsManager0002Test::addMenu_SingleArticle_MenuAdded
SeleniumClient\WebDriverWaitTimeoutException: Timeout for specified condition caused by object of class: SeleniumClient\WebDriver, method invoked: findElement. Arguments: <By strategy: 'xpath', strategy factor '//ul/li/a[@href='index.php?option=com_content']'>,<1>

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriverWait.php:91
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:416
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminPage.php:192
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/JoomlaWebdriverTestCase.php:83
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Content/ArticleManagerPage.php:107
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0002Test.php:106

4) MenuItemsManager0002Test::addMenu_CategoryBlog_MenuAdded
SeleniumClient\WebDriverWaitTimeoutException: Timeout for specified condition caused by object of class: SeleniumClient\WebDriver, method invoked: findElement. Arguments: <By strategy: 'xpath', strategy factor '//ul/li/a[@href='index.php?option=com_content']'>,<1>

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriverWait.php:91
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:416
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminPage.php:192
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/JoomlaWebdriverTestCase.php:83
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Content/ArticleManagerPage.php:107
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0002Test.php:178

5) MenuItemsManager0002Test::addMenu_CategoryList_MenuAdded
SeleniumClient\WebDriverWaitTimeoutException: Timeout for specified condition caused by object of class: SeleniumClient\WebDriver, method invoked: findElement. Arguments: <By strategy: 'xpath', strategy factor '//ul/li/a[@href='index.php?option=com_content']'>,<1>

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriverWait.php:91
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:416
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminPage.php:192
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/JoomlaWebdriverTestCase.php:83
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Content/ArticleManagerPage.php:107
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0002Test.php:272

6) MenuItemsManager0004Test::addMenuItem_SingleNewsFeed_MenuItemAdded
SeleniumClient\WebDriverWaitTimeoutException: Timeout for specified condition caused by object of class: SeleniumClient\WebDriver, method invoked: findElement. Arguments: <By strategy: 'xpath', strategy factor '//a[contains(text(),'Joomla! Connect')]'>,<1>

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriverWait.php:91
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:416
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/SiteContent/SiteContentFeaturedPage.php:164
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0004Test.php:139

7) MenuItemsManager0004Test::addMenuItem_ListAllNewsFeedCategory_MenuAdded
SeleniumClient\Http\SeleniumNoSuchElementException:  An element could not be located on the page using the given search parameters. Unable to locate element: {"method":"xpath","selector":"//thead//input[@name='checkall-toggle' or @name='toggle']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'puneet-ThinkPad-T430', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.13.0-43-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown

/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:73
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/Http/SeleniumAdapter.php:26
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/SeleniumClient/WebDriver.php:350
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/System/AdminManagerPage.php:38
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/Pages/Menus/MenuItemsManagerPage.php:177
/home/puneet/Projects/GSOC-Webdriver_system_tests_for_CMS/tests/system/webdriver/tests/menus/MenuItemsManager0004Test.php:217

FAILURES!
Tests: 24, Assertions: 1179, Errors: 7.

**Comment by kshitijSharma2014** [comment]
@puneet0191 thanks,  running the tests again

**Comment by kshitijSharma2014** [comment]
@puneet0191  please close this PR as I have done a new PR on menus. https://github.com/joomla-projects/GSOC-Webdriver_system_tests_for_CMS/pull/103 

Also I am not getting these many errors, I got only one and I have resolved it in the new PR.

**Comment by puneet0191** [comment]
@kshitijSharma2014  Closing this one, creating a new Issue for verfying Failures in Menus tests

**Pull request closed without merging**
