### PR TITLE
Current issues

### PR DESCRIPTION
**Pull request by kshitijSharma2014**

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@puneet0191  @javigomez  please review this PR.
Unnecessary tags were present which caused the test to break.

**Comment by javigomez** [comment]
please @puneet0191 review and merge when you have the chance

**Comment by puneet0191** [comment]
I just ran the tests without your fixes this morning, I didn't get any errors in ArticleManager0001Tests.php, for the tabs issue

**Comment by puneet0191** [comment]
@kshitijSharma2014 Closing this, if required we can re-do the PR again

**Pull request closed without merging**
