### PR TITLE
Update ArticleManager0003Test.php

### PR DESCRIPTION
**Pull request by kshitijSharma2014**

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@puneet0191 
made some changes in this file

**Comment by puneet0191** [comment]
What was the need for this changes?, was it causing any failures or errors?

**Comment by kshitijSharma2014** [comment]
@puneet0191 
It was causing an error as there was no command to do admin login
also the line I removed was useless as it was redirecting to the sitepage unnecessarily

**Comment by puneet0191** [comment]
Thanks

**Pull request merged**
